### ISSUE TITLE
0.01 = 0.18 or 0.125? wrong calcuation with 0.0xx values

### ISSUE THREAD

**Issue by fastrizwaan** [war1025/GCalcSearch#1]
try this:

21000 \* 0.07 %

which should get = 14.7

but with advanced calculator

http://imageshack.us/f/4/wrongcalculation.png/

**Comment by war1025** [comment]
This issue is fixed as of commit 6c09eff...

The new version is available both on the gnome shell extensions site and the downloads section on github.
