### ISSUE TITLE
GCalcSearch defaults to degrees

### ISSUE THREAD

**Issue by siefkenj** [war1025/GCalcSearch#4]
I am not sure if this is on purpose or not, but GCalcSearch defaults to degrees.  "sin('pi')" does not return zero as might be expected.

**Comment by war1025** [comment]
gcalctool seems to default to degrees and I don't know that there is a command line switch to change to radians. I'll look into it. Sorry for the delayed response

**Comment by Visgean** [comment]
There should also be possibility to convert degrees to radians and vice versa...

**Comment by war1025** [comment]
I have added the ability to use radians by prefixing trig functions with `r`. For example `rsin('pi'/2)` results in `1` as expected. `rasin(1)` results in `1.57...` as expected.
