### ISSUE TITLE
gjs-console jumps to 100%CPU after a computation

### ISSUE THREAD

**Issue by norbusan** [war1025/GCalcSearch#5]
Hi,

first of all thanks for the nice extension. Unfortunately I can repeat the following problem:
- go into the overview mode
- make a simple computation
- wait that the answer is shown
- ESC/Enter to leave
  after that gjs-console consumes 100%CPU.

I checked that I am using the latest version from git
gnome-shell 3.4.1

Thanks a lot and all the best

Norbert

**Comment by war1025** [comment]
I can't seem to reproduce this. Can you think of anything else that is going on that might contribute? Does the issue go away if you disable the extension?

**Comment by norbusan** [comment]
I was playing around for quite some time and I think I found the reason: it is tracker/gnome-documents.
After disabling any search of tracker the problem disappears. I guess we can close this issue,

Sorry for the noise.

Norbert
